apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinkit-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blinkit-backend
  template:
    metadata:
      labels:
        app: blinkit-backend
    spec:
      containers:
      - name: backend
        image: 746486152802.dkr.ecr.us-east-1.amazonaws.com/blinkit-backend:v51
        ports:
        - containerPort: 8090
        # Fetches PORT and FRONTEND_URL
        envFrom:
        - configMapRef:
            name: blinkit-all-config
        # Fetches all sensitive keys
        env:
        - name: MONGODB_URI
          valueFrom: { secretKeyRef: { name: blinkit-all-secrets, key: MONGO_URI } }
        - name: RESEND_API
          valueFrom: { secretKeyRef: { name: blinkit-all-secrets, key: RESEND_API } }
        - name: VITE_STRIPE_PUBLIC_KEY
          valueFrom: { secretKeyRef: { name: blinkit-all-secrets, key: VITE_STRIPE_PUBLIC_KEY } }
        - name: STRIPE_SECRET_KEY
          valueFrom: { secretKeyRef: { name: blinkit-all-secrets, key: STRIPE_SECRET_KEY } }
        - name: STRIPE_ENPOINT_WEBHOOK_SECRET_KEY
          valueFrom: { secretKeyRef: { name: blinkit-all-secrets, key: STRIPE_ENPOINT_WEBHOOK_SECRET_KEY } }
        - name: SECRET_KEY_REFRESH_TOKEN
          valueFrom: { secretKeyRef: { name: blinkit-all-secrets, key: SECRET_KEY_REFRESH_TOKEN } }
        - name: SECRET_KEY_ACCESS_TOKEN
          valueFrom: { secretKeyRef: { name: blinkit-all-secrets, key: SECRET_KEY_ACCESS_TOKEN } }
---
apiVersion: v1
kind: Service
metadata:
  name: blinkit-backend-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: blinkit-backend