apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinkit-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blinkit-frontend
  template:
    metadata:
      labels:
        app: blinkit-frontend
    spec:
      containers:
      - name: frontend
        image: 746486152802.dkr.ecr.us-east-1.amazonaws.com/blinkit-frontend:v48
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blinkit-frontend-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: blinkit-frontend